Dev nap
rabbotio/nap pull request #1
Opened 2017-05-02 09:49 UTC by ArtNattapat

change NAP.config to require('./config')
move nap's graphql to server/graphql
graphql can serve only 1 endpoint now (from multi endpoint by sub-directory)
extend support by global.NAP.expose (see graphq/setup.example.js for more example)

2017-05-02 10:44 UTC, katopz requested changes

2017-05-02 10:44 UTC, katopz commented on graphql/setup.example.js
> +      resolve: () => 'HEllo',
Please correct `HEllo` to `Hello`

2017-05-02 10:44 UTC, katopz commented on graphql/setup.example.js
> +    sss: {
Please change `sss` to `foo`

2017-05-02 10:44 UTC, katopz commented on examples/module/index.js
> +      sss: {
Please change `sss` to `foo`

2017-05-02 10:44 UTC, katopz commented on lib/nap-plugin-oauth/README.md
> +```ts
Please change `ts` to `js`

2017-05-02 10:44 UTC, katopz commented on server/config.js
> +  passportEnabled: int(process.env.PASSPORT_DISABLED || '0') === 0,
`Passport` is opt-out service so please use `passport_disabled` instead

2017-05-02 10:44 UTC, katopz commented on server/config.js
> +  graphqlEnabled: true,
`GraphQL` is opt-out service so please use `graphql_disabled` instead

2017-05-02 10:44 UTC, katopz commented on server/config.js
> +  graphqliqlEnabled: true,
`GraphiQL` should enable by default in dev mode and opt-in at prod please use `graphiql_enabled` and respect `process.env.GRAPHIQL_ENABLED`

2017-05-02 10:44 UTC, katopz commented on server/config.js
> +  mubsub: process.env.TRIGGER_MUBSUB,
`mubsub` should be optional and opt-in

2017-05-02 10:44 UTC, katopz commented on server/index.js
> +  return nextjs.prepare().then(() => initializer(config, nextjs)).catch(console.log)
Please remove `console.log`

2017-05-02 10:44 UTC, katopz commented on server/initializer.js
> +  config.passportEnabled && require('./initPassport')(config, app, nextjs)
Please replace `(config, app, nextjs)` with `(config, app)`

2017-05-02 10:44 UTC, katopz commented on templates/email-register.js
> +})
This file should be delete (deprecated)

2017-05-02 11:15 UTC, ArtNattapat commented on examples/module/index.js
> +      sss: {
this file deprecated. i will remove on next commit.

2017-05-03 04:16 UTC, ArtNattapat commented on lib/nap-plugin-oauth/README.md
> +```ts
this example written by typescript. should it be ts format ?

2017-05-03 04:19 UTC, katopz commented on lib/nap-plugin-oauth/README.md
> +```ts
Please also provide `js` example.

2017-05-03 05:01 UTC, katopz requested changes

2017-05-03 05:01 UTC, katopz commented on server/initializer.js
> +  !config.passport_disabled && require('./initPassport')(config, app, nextjs)
Please change `(config, app, nextjs)` to `(config, app)`

2017-05-03 05:12 UTC, katopz approved these changes

2017-05-03 05:14 UTC, merged